=== UO307240/sew/xml/etapa.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT etapa (datos_basicos, referencias, multimedia, itinerario, clasificaciones)>

<!ELEMENT datos_basicos (nombre, numero, fecha, tipo, distancia, desnivel, ganador)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidades CDATA #REQUIRED>
<!ELEMENT ganador (nombre_ciclista, tiempo, velocidad)>
<!ELEMENT nombre_ciclista (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ATTLIST velocidad unidades CDATA #REQUIRED>

<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT multimedia (fotografias, videos, podcasts)>
<!ELEMENT fotografias (fotografia, fotografia?, fotografia?, fotografia?, fotografia?)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT videos (video, video?, video?)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT podcasts (podcast, podcast?, podcast?)>
<!ELEMENT podcast (#PCDATA)>

<!ELEMENT itinerario (salida, meta, hitos, puntos_paso)>

<!ELEMENT coordenadas (latitud, longitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidades CDATA #REQUIRED>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidades CDATA #REQUIRED>

<!ELEMENT salida (poblacion, coordenadas)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT meta (poblacion, coordenadas)>

<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre_hito, coordenadas, distancia_salida)>
<!ELEMENT nombre_hito (#PCDATA)>
<!ELEMENT distancia_salida (#PCDATA)>
<!ATTLIST distancia_salida unidades CDATA #REQUIRED>
<!ATTLIST hito tipo (puerto_1 | puerto_2 | puerto_3 | puerto_especial | puerto_bonificado | sprint_intermedio | sprint_bonificado) #REQUIRED>

<!ELEMENT puntos_paso (punto_paso+)>
<!ELEMENT punto_paso (coordenadas, distancia_salida)>
<!ATTLIST punto_paso nombre CDATA #IMPLIED>

<!ELEMENT clasificaciones (clasificacion_etapa, clasificacion_general, clasificacion_equipos)>

<!ELEMENT clasificacion_etapa (ciclista_etapa, ciclista_etapa, ciclista_etapa)>
<!ELEMENT ciclista_etapa (nombre_ciclista, equipo, posicion, diferencia_tiempo?)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT diferencia_tiempo (#PCDATA)>

<!ELEMENT clasificacion_general (ciclista_general, ciclista_general, ciclista_general)>
<!ELEMENT ciclista_general (nombre_ciclista, equipo, posicion, diferencia_tiempo?)>

<!ELEMENT clasificacion_equipos (equipo_clasificado, equipo_clasificado, equipo_clasificado)>
<!ELEMENT equipo_clasificado (nombre_equipo, posicion, diferencia_tiempo?)>
<!ELEMENT nombre_equipo (#PCDATA)>

=== UO307240/sew/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
<etapa>

    <datos_basicos>
        <nombre>Cartagena a Lorca</nombre>
        <numero>11</numero>
        <fecha>2026-09-02</fecha>
        <tipo>Llana</tipo>
        <distancia unidades="km">153.8</distancia>
        <desnivel unidades="m">1351</desnivel>
        <ganador>
            <nombre_ciclista>Jasper Philipsen</nombre_ciclista>
            <tiempo>03:25:04</tiempo>
            <velocidad unidades="km/h">44.97</velocidad>
        </ganador>
    </datos_basicos>

    <referencias>
        <referencia>https://www.cartagena.es</referencia>
        <referencia>https://www.lorca.es</referencia>
        <referencia>https://www.carm.es</referencia>
    </referencias>

    <multimedia>
        <fotografias>
            <fotografia>multimedia/salida_cartagena.jpg</fotografia>
            <fotografia>multimedia/puerto_aledo.jpg</fotografia>
            <fotografia>multimedia/meta_lorca.jpg</fotografia>
        </fotografias>
        <videos>
            <video>multimedia/resumen_etapa11.mp4</video>
        </videos>
        <podcasts>
            <podcast>multimedia/audio_etapa11.mp3</podcast>
        </podcasts>
    </multimedia>

    <itinerario>
        <salida>
            <poblacion>Cartagena</poblacion>
            <coordenadas>
                <latitud unidades="grados">37.59944</latitud>
                <longitud unidades="grados">-0.97692</longitud>
                <altitud unidades="m">39</altitud>
            </coordenadas>
        </salida>

        <meta>
            <poblacion>Lorca</poblacion>
            <coordenadas>
                <latitud unidades="grados">37.66017</latitud>
                <longitud unidades="grados">-1.70456</longitud>
                <altitud unidades="m">337</altitud>
            </coordenadas>
        </meta>

        <hitos>
            <hito tipo="sprint_bonificado">
                <nombre_hito>Sprint Intermedio Totana</nombre_hito>
                <coordenadas>
                    <latitud unidades="grados">37.77110</latitud>
                    <longitud unidades="grados">-1.50000</longitud>
                    <altitud unidades="m">225</altitud>
                </coordenadas>
                <distancia_salida unidades="km">111.9</distancia_salida>
            </hito>
            <hito tipo="puerto_3">
                <nombre_hito>Alto de Aledo</nombre_hito>
                <coordenadas>
                    <latitud unidades="grados">37.79250</latitud>
                    <longitud unidades="grados">-1.57390</longitud>
                    <altitud unidades="m">623</altitud>
                </coordenadas>
                <distancia_salida unidades="km">121.8</distancia_salida>
            </hito>
        </hitos>

        <puntos_paso>
            <punto_paso nombre="Los Nietos">
                <coordenadas>
                    <latitud unidades="grados">37.64330</latitud>
                    <longitud unidades="grados">-0.83500</longitud>
                    <altitud unidades="m">10</altitud>
                </coordenadas>
                <distancia_salida unidades="km">23.0</distancia_salida>
            </punto_paso>
            <punto_paso nombre="Los Alcázares">
                <coordenadas>
                    <latitud unidades="grados">37.74440</latitud>
                    <longitud unidades="grados">-0.84970</longitud>
                    <altitud unidades="m">10</altitud>
                </coordenadas>
                <distancia_salida unidades="km">36.2</distancia_salida>
            </punto_paso>
            <punto_paso nombre="Torre-Pacheco">
                <coordenadas>
                    <latitud unidades="grados">37.74280</latitud>
                    <longitud unidades="grados">-0.96110</longitud>
                    <altitud unidades="m">36</altitud>
                </coordenadas>
                <distancia_salida unidades="km">48.5</distancia_salida>
            </punto_paso>
            <punto_paso nombre="Fuente Álamo de Murcia">
                <coordenadas>
                    <latitud unidades="grados">37.72030</latitud>
                    <longitud unidades="grados">-1.17110</longitud>
                    <altitud unidades="m">128</altitud>
                </coordenadas>
                <distancia_salida unidades="km">75.9</distancia_salida>
            </punto_paso>
        </puntos_paso>
    </itinerario>

    <clasificaciones>
        <clasificacion_etapa>
            <ciclista_etapa>
                <nombre_ciclista>Jasper Philipsen</nombre_ciclista>
                <equipo>Alpecin-Premier Tech</equipo>
                <posicion>1</posicion>
            </ciclista_etapa>
            <ciclista_etapa>
                <nombre_ciclista>Kaden Groves</nombre_ciclista>
                <equipo>Alpecin-Premier Tech</equipo>
                <posicion>2</posicion>
                <diferencia_tiempo>+00:00:02</diferencia_tiempo>
            </ciclista_etapa>
            <ciclista_etapa>
                <nombre_ciclista>Wout van Aert</nombre_ciclista>
                <equipo>Team Visma | Lease a Bike</equipo>
                <posicion>3</posicion>
                <diferencia_tiempo>+00:00:02</diferencia_tiempo>
            </ciclista_etapa>
        </clasificacion_etapa>

        <clasificacion_general>
            <ciclista_general>
                <nombre_ciclista>Primož Roglič</nombre_ciclista>
                <equipo>Red Bull - BORA - hansgrohe</equipo>
                <posicion>1</posicion>
            </ciclista_general>
            <ciclista_general>
                <nombre_ciclista>Enric Mas</nombre_ciclista>
                <equipo>Movistar Team</equipo>
                <posicion>2</posicion>
                <diferencia_tiempo>+00:00:05</diferencia_tiempo>
            </ciclista_general>
            <ciclista_general>
                <nombre_ciclista>Richard Carapaz</nombre_ciclista>
                <equipo>EF Education - EasyPost</equipo>
                <posicion>3</posicion>
                <diferencia_tiempo>+00:00:12</diferencia_tiempo>
            </ciclista_general>
        </clasificacion_general>

        <clasificacion_equipos>
            <equipo_clasificado>
                <nombre_equipo>Red Bull - BORA - hansgrohe</nombre_equipo>
                <posicion>1</posicion>
            </equipo_clasificado>
            <equipo_clasificado>
                <nombre_equipo>Movistar Team</nombre_equipo>
                <posicion>2</posicion>
                <diferencia_tiempo>+00:00:45</diferencia_tiempo>
            </equipo_clasificado>
            <equipo_clasificado>
                <nombre_equipo>UAE Team Emirates XRG</nombre_equipo>
                <posicion>3</posicion>
                <diferencia_tiempo>+00:01:10</diferencia_tiempo>
            </equipo_clasificado>
        </clasificacion_equipos>
    </clasificaciones>

</etapa>
